#!/usr/bin/env python3
"""Split a full gomarkdoc output into the 7 per-module camera.ui Go SDK pages.

Usage:
    python3 split_api_docs.py <full_md_in> <out_dir>

The full markdown is structured as:

    # sdk
    ## Index ...
    ## Constants ...
    ## Variables ...
    ## func Foo
    ## type Bar
        ### func NewBar
        ### func (b *Bar) Method
    ...

Each top-level `## type X` or `## func X` heading defines one symbol. We
route each symbol to exactly one of the 7 logical buckets defined in
BUCKETS below. Methods (`### func (...)`) are kept under their parent
type. Anything not in BUCKETS is dropped.

Each output page gets:
  * a curated intro paragraph (PAGE_INTROS)
  * the gomarkdoc bodies for the symbols routed to it
  * a top-of-page note that the body is generated by gomarkdoc

Constants and Variables are appended to the `types.md` bucket since they
don't have type-level homes.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Symbol name -> module page (filename without .md).
BUCKETS: dict[str, str] = {
    # plugin.md — lifecycle, contract, optional interfaces, helpers
    "Plugin": "plugin",
    "BasePlugin": "plugin",
    "NewBasePlugin": "plugin",
    "PluginAPI": "plugin",
    "PluginContract": "plugin",
    "PluginInfo": "plugin",
    "PythonVersion": "plugin",
    "PluginRole": "plugin",
    "PluginInterface": "plugin",
    "PluginStatus": "plugin",
    "PluginStorage": "plugin",
    "PluginAssignments": "plugin",
    "AssignedPlugin": "plugin",
    "APIEvent": "plugin",
    "StorageSchemaProvider": "plugin",
    "Run": "plugin",
    "GetContractValidationErrors": "plugin",
    "ValidateContractConsistency": "plugin",
    "IsHub": "plugin",
    "CanCreateCameras": "plugin",
    "CanProvideSensorsToAnyCameras": "plugin",
    "HasInterface": "plugin",
    # Optional interfaces
    "DiscoveryProvider": "plugin",
    "DiscoveredCamera": "plugin",
    "NotifierInterface": "plugin",
    "NotifierDevice": "plugin",
    "Notification": "plugin",
    "Severity": "plugin",
    "PluginCapability": "plugin",
    "CapabilityPublishNotifications": "plugin",
    "HasCapability": "plugin",
    "MotionDetectionInterface": "plugin",
    "MotionDetectionResponse": "plugin",
    "MotionDetectionSettings": "plugin",
    "ObjectDetectionInterface": "plugin",
    "ObjectDetectionResponse": "plugin",
    "ObjectDetectionSettings": "plugin",
    "AudioDetectionInterface": "plugin",
    "AudioDetectionResponse": "plugin",
    "AudioDetectionSettings": "plugin",
    "FaceDetectionInterface": "plugin",
    "FaceDetectionResponse": "plugin",
    "LicensePlateDetectionInterface": "plugin",
    "LicensePlateDetectionResponse": "plugin",
    "ClassifierDetectionInterface": "plugin",
    "ClassifierDetectionResponse": "plugin",
    "ClipDetectionInterface": "plugin",
    "ClipTextEmbeddingResult": "plugin",
    "OAuthCapable": "plugin",
    "OAuthDeviceFlowCapable": "plugin",
    "OAuthAuthCodeFlowCapable": "plugin",
    "OAuthClientCredentialsCapable": "plugin",
    "OAuthState": "plugin",
    "OAuthStatus": "plugin",
    "OAuthMetadata": "plugin",
    "OAuthProviderConfig": "plugin",
    "OAuthProviderDeclaration": "plugin",
    "ImageMetadata": "plugin",
    "AudioMetadata": "plugin",
    # camera.md — camera entities, sources, frames, streaming
    "Camera": "camera",
    "BaseCamera": "camera",
    "CameraConfig": "camera",
    "BaseCameraConfig": "camera",
    "CameraConfigInputSettings": "camera",
    "CameraDevice": "camera",
    "CameraDeviceSource": "camera",
    "CameraInput": "camera",
    "CameraInformation": "camera",
    "CameraPluginInfo": "camera",
    "CameraType": "camera",
    "CameraRole": "camera",
    "CameraAspectRatio": "camera",
    "CameraDetectionSettings": "camera",
    "CameraFrameWorkerSettings": "camera",
    "CameraUiSettings": "camera",
    "DetectionZone": "camera",
    "DetectionLine": "camera",
    "LineDirection": "camera",
    "ZoneType": "camera",
    "ZoneFilter": "camera",
    "Point": "camera",
    "MotionResolution": "camera",
    "PtzAutotrackSettings": "camera",
    "SnapshotSettings": "camera",
    "SnapshotInterface": "camera",
    "StreamingInterface": "camera",
    "StreamingRole": "camera",
    "VideoStreamingMode": "camera",
    "StreamUrls": "camera",
    "FMTPInfo": "camera",
    "AudioCodecProperties": "camera",
    "VideoCodecProperties": "camera",
    "ProbeConfig": "camera",
    "StreamDirection": "camera",
    "Go2RtcWSSource": "camera",
    "Go2RtcRTSPSource": "camera",
    "Go2RtcSnapshotSource": "camera",
    "RTSPAudioCodec": "camera",
    "ProbeAudioCodec": "camera",
    "AudioCodec": "camera",
    "AudioFFmpegCodec": "camera",
    "VideoCodec": "camera",
    "VideoFFmpegCodec": "camera",
    "RTSPUrlOptions": "camera",
    "SnapshotUrlOptions": "camera",
    "BuildTargetUrl": "camera",
    "BuildSnapshotUrl": "camera",
    "ProbeStream": "camera",
    "VideoStreamInfo": "camera",
    "AudioStreamInfo": "camera",
    "VideoFrameData": "camera",
    "FrameFormat": "camera",
    "DetectionEvent": "camera",
    "DetectionEventData": "camera",
    "DetectionEventType": "camera",
    "DetectionEventState": "camera",
    "PropertyChangeEvent": "camera",
    "RecordingState": "camera",
    "RecordingStatus": "camera",
    "RecordingSegment": "camera",
    "CallbackInvoker": "camera",
    "PTZCapability": "camera",
    "PTZDirection": "camera",
    "PTZPosition": "camera",
    # sensor.md — sensors (detection + smart-home)
    "Sensor": "sensor",
    "BaseSensor": "sensor",
    "NewBaseSensor": "sensor",
    "SensorType": "sensor",
    "SensorCategory": "sensor",
    "BoundingBox": "sensor",
    "Detection": "sensor",
    "DetectionLabel": "sensor",
    "DetectionAttribute": "sensor",
    "TrackedDetection": "sensor",
    "TrackVelocity": "sensor",
    "ModelSpec": "sensor",
    "ObjectModelSpec": "sensor",
    "AudioModelSpec": "sensor",
    "AudioFormat": "sensor",
    "AudioFrameData": "sensor",
    "AudioLabel": "sensor",
    "AudioResult": "sensor",
    "AudioDetector": "sensor",
    "AudioSensor": "sensor",
    "NewAudioSensor": "sensor",
    "AudioDetectorSensor": "sensor",
    "NewAudioDetectorSensor": "sensor",
    "MotionDetector": "sensor",
    "MotionResult": "sensor",
    "MotionSensor": "sensor",
    "NewMotionSensor": "sensor",
    "MotionDetectorSensor": "sensor",
    "NewMotionDetectorSensor": "sensor",
    "ObjectDetector": "sensor",
    "ObjectResult": "sensor",
    "ObjectSensor": "sensor",
    "NewObjectSensor": "sensor",
    "ObjectDetectorSensor": "sensor",
    "NewObjectDetectorSensor": "sensor",
    "FaceDetection": "sensor",
    "FaceResult": "sensor",
    "FaceDetector": "sensor",
    "FaceSensor": "sensor",
    "NewFaceSensor": "sensor",
    "FaceDetectorSensor": "sensor",
    "NewFaceDetectorSensor": "sensor",
    "LicensePlateDetection": "sensor",
    "LicensePlateResult": "sensor",
    "LicensePlateDetector": "sensor",
    "LicensePlateSensor": "sensor",
    "NewLicensePlateSensor": "sensor",
    "LicensePlateDetectorSensor": "sensor",
    "NewLicensePlateDetectorSensor": "sensor",
    "ClassifierDetection": "sensor",
    "ClassifierResult": "sensor",
    "ClassifierDetector": "sensor",
    "ClassifierSensor": "sensor",
    "NewClassifierSensor": "sensor",
    "ClassifierDetectorSensor": "sensor",
    "NewClassifierDetectorSensor": "sensor",
    "ClipEmbedding": "sensor",
    "ClipResult": "sensor",
    "ClipDetector": "sensor",
    "ClipDetectorSensor": "sensor",
    "NewClipDetectorSensor": "sensor",
    "BatteryInfo": "sensor",
    "NewBatteryInfo": "sensor",
    "ChargingState": "sensor",
    "ContactSensor": "sensor",
    "NewContactSensor": "sensor",
    "DoorbellTrigger": "sensor",
    "NewDoorbellTrigger": "sensor",
    "GarageControl": "sensor",
    "NewGarageControl": "sensor",
    "GarageState": "sensor",
    "HumidityInfo": "sensor",
    "NewHumidityInfo": "sensor",
    "LeakSensor": "sensor",
    "NewLeakSensor": "sensor",
    "LightControl": "sensor",
    "NewLightControl": "sensor",
    "LockControl": "sensor",
    "NewLockControl": "sensor",
    "LockState": "sensor",
    "OccupancySensor": "sensor",
    "NewOccupancySensor": "sensor",
    "PTZControl": "sensor",
    "NewPTZControl": "sensor",
    "SecuritySystem": "sensor",
    "NewSecuritySystem": "sensor",
    "SecuritySystemState": "sensor",
    "SirenControl": "sensor",
    "NewSirenControl": "sensor",
    "SmokeSensor": "sensor",
    "NewSmokeSensor": "sensor",
    "SwitchControl": "sensor",
    "NewSwitchControl": "sensor",
    "TemperatureInfo": "sensor",
    "NewTemperatureInfo": "sensor",
    "SensorTriggerRef": "sensor",
    "SensorTriggerSettings": "sensor",
    # storage.md — schema-driven config
    "DeviceStorage": "storage",
    "JsonSchema": "storage",
    "JsonSchemaType": "storage",
    "StringFormat": "storage",
    "SchemaCondition": "storage",
    "SchemaConditionOperator": "storage",
    "ButtonColor": "storage",
    "FormSubmitResponse": "storage",
    "ToastMessage": "storage",
    "ToastType": "storage",
    "StorageStats": "storage",
    "CameraStorageStats": "storage",
    "StorageController": "storage",
    # manager.md — system services
    "CoreManager": "manager",
    "CoreManagerEvent": "manager",
    "DeviceManager": "manager",
    "DownloadManager": "manager",
    "DownloadToken": "manager",
    "DownloadCleanup": "manager",
    "CreateDownloadOptions": "manager",
    "NotificationManager": "manager",
    "CreateStreamDownloadOptions": "manager",
    # observable.md — reactive primitives
    "Observable": "observable",
    "NewObservable": "observable",
    "Subject": "observable",
    "NewSubject": "observable",
    "BehaviorSubject": "observable",
    "NewBehaviorSubject": "observable",
    "ReplaySubject": "observable",
    "NewReplaySubject": "observable",
    "Disposable": "observable",
    "NewDisposable": "observable",
    "Subscribable": "observable",
    "FirstValueFrom": "observable",
    "DistinctUntilChanged": "observable",
    "DistinctUntilChangedFunc": "observable",
    "Filter": "observable",
    "Map": "observable",
    "MergeMap": "observable",
    "Pairwise": "observable",
    "Share": "observable",
    # types.md — shared utilities, helpers
    "Logger": "types",
    "Bool": "types",
    "Int": "types",
    "Float64": "types",
}

DROP: set[str] = {
    "EventAttribute",
    "EventDescription",
    "EventDetection",
    "EventSegment",
    "EventTrigger",
    "EventTriggerType",
}

PAGE_TITLES: dict[str, str] = {
    "plugin": "Plugin API",
    "camera": "Camera",
    "sensor": "Sensors",
    "storage": "Storage & Schema",
    "manager": "Manager",
    "observable": "Observable",
    "types": "Types",
}

PAGE_INTROS: dict[str, str] = {
    "plugin": (
        "Core plugin lifecycle and capability surface: the `Plugin` interface every "
        "plugin implements, the `BasePlugin` boilerplate-saver, the `PluginContract` "
        "manifest, lifecycle event names (`APIEvent*`), and every optional interface — "
        "`DiscoveryProvider`, `NotifierInterface`, and the seven detection interfaces."
    ),
    "camera": (
        "Camera entities and runtime device API: `CameraDevice` (the per-camera handle "
        "your plugin receives in `ConfigureCameras`), camera sources, snapshots, "
        "streaming URL helpers, video frame data, detection events, and the property-"
        "change observables."
    ),
    "sensor": (
        "Detection sensors (motion, object, face, license-plate, audio, classifier, "
        "clip) and smart-home sensors (contact, doorbell, lock, garage, light, switch, "
        "PTZ, security system, environmental). Plus the sensor-level model specs and "
        "shared detection types (`Detection`, `BoundingBox`, `TrackedDetection`)."
    ),
    "storage": (
        "Schema-driven configuration store rendered as UI forms by the host. "
        "`DeviceStorage` exposes the schema definition / read / write API; `JsonSchema` "
        "and friends describe individual fields, conditional visibility, and submit-"
        "form responses."
    ),
    "manager": (
        "System-level services injected onto `PluginAPI`: `CoreManager` for FFmpeg "
        "path / inter-plugin RPC / cloud signing, `DeviceManager` for camera lookup "
        "and async discovery, `DownloadManager` for token-protected downloads, and "
        "`NotificationManager` for publishing notifications into the host."
    ),
    "observable": (
        "Lightweight reactive primitives: `Observable`, `Subject`, `BehaviorSubject`, "
        "`ReplaySubject`, the `Disposable` subscription handle, and a small set of "
        "composable operators (`Map`, `Filter`, `DistinctUntilChanged`, `Pairwise`, …)."
    ),
    "types": (
        "Shared utility types: the `Logger` interface every plugin and camera exposes, "
        "and pointer-helper functions (`Bool`, `Int`, `Float64`) used by JSON schemas "
        "with optional numeric / boolean fields."
    ),
}


def parse_index(text: str) -> int:
    """Find the line index where the gomarkdoc header (Index) ends."""
    # Index ends at the first heading after `## Index` that's not a sub-bullet.
    # The simplest landmark is the "## Constants" / "## Variables" line — which
    # both come before the first symbol heading.
    for i, line in enumerate(text.splitlines()):
        if (
            line.startswith("## Constants")
            or line.startswith("## func ")
            or line.startswith("## type ")
        ):
            return i
    return 0


def split_into_blocks(text: str) -> list[tuple[str, str]]:
    """Split the markdown into (kind+name, body) blocks.

    Each block starts at a `## ` heading. The first block starts at
    `## Constants` or the first symbol; everything before that is dropped.
    """
    body_start = parse_index(text)
    body_lines = text.splitlines()[body_start:]

    blocks: list[tuple[str, str]] = []
    current_key: str | None = None
    current_buf: list[str] = []

    heading_re = re.compile(
        r"^## (Constants|Variables|func ([A-Za-z0-9_]+)|type ([A-Za-z0-9_]+))"
    )

    for line in body_lines:
        m = heading_re.match(line)
        if m:
            # Flush previous block.
            if current_key is not None:
                blocks.append((current_key, "\n".join(current_buf).rstrip() + "\n"))
            kind = m.group(1)
            if kind == "Constants" or kind == "Variables":
                current_key = kind
            elif kind.startswith("func "):
                current_key = f"func:{m.group(2)}"
            else:
                current_key = f"type:{m.group(3)}"
            current_buf = [line]
        else:
            if current_key is not None:
                current_buf.append(line)
    if current_key is not None:
        blocks.append((current_key, "\n".join(current_buf).rstrip() + "\n"))

    return blocks


def bucket_for(key: str) -> str | None:
    """Map a block key to its bucket name, or None if it should be dropped."""
    if key in ("Constants", "Variables"):
        return "types"
    if not key.startswith(("func:", "type:")):
        return None
    name = key.split(":", 1)[1]
    if name in DROP:
        return None
    return BUCKETS.get(name)


def render_page(bucket: str, blocks: list[tuple[str, str]]) -> str:
    """Render one per-module markdown page."""
    title = PAGE_TITLES[bucket]
    intro = PAGE_INTROS[bucket]
    parts: list[str] = [
        f"# {title}",
        "",
        intro,
        "",
        "!!! note",
        "    The reference below is auto-generated from Go doc comments via "
        "[`gomarkdoc`](https://github.com/princjef/gomarkdoc). Re-run "
        "`scripts/gen-api-docs.sh` to refresh it.",
        "",
    ]
    for _, body in blocks:
        parts.append(body.rstrip())
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    if len(sys.argv) != 3:
        print("usage: split_api_docs.py <full_md> <out_dir>", file=sys.stderr)
        sys.exit(2)

    full_md_path = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    text = full_md_path.read_text(encoding="utf-8")
    blocks = split_into_blocks(text)

    by_bucket: dict[str, list[tuple[str, str]]] = {b: [] for b in PAGE_TITLES}
    for key, body in blocks:
        bucket = bucket_for(key)
        if bucket is None:
            continue
        by_bucket[bucket].append((key, body))

    for bucket, blist in by_bucket.items():
        out_file = out_dir / f"{bucket}.md"
        out_file.write_text(render_page(bucket, blist), encoding="utf-8")
        print(
            f"  wrote {out_file.relative_to(out_dir.parent.parent)}  ({len(blist)} blocks)"
        )


if __name__ == "__main__":
    main()
