from __future__ import annotations

from .api import API_EVENT, APIListener, PluginAPI
from .contract import PluginCapability, PluginContract, PluginInfo, PluginInterface, PluginRole, PythonVersion
from .helper import (
    can_create_cameras,
    can_provide_sensors_to_any_cameras,
    get_contract_validation_errors,
    has_capability,
    has_interface,
    is_hub,
    validate_contract_consistency,
)
from .interfaces import (
    AudioDetectionInterface,
    AudioDetectionPluginResponse,
    AudioMetadata,
    BasePlugin,
    ClassifierDetectionInterface,
    ClassifierDetectionPluginResponse,
    ClipDetectionInterface,
    ClipDetectionPluginResponse,
    ClipTextEmbeddingResult,
    DiscoveryProvider,
    FaceDetectionInterface,
    FaceDetectionPluginResponse,
    ImageMetadata,
    LicensePlateDetectionInterface,
    LicensePlateDetectionPluginResponse,
    MotionDetectionInterface,
    MotionDetectionPluginResponse,
    ObjectDetectionInterface,
    ObjectDetectionPluginResponse,
    PluginInterfaces,
)
from .notifier import (
    Notification,
    NotifierDevice,
    NotifierInterface,
    Severity,
)
from .oauth import (
    OAuthAuthCodeFlowCapable,
    OAuthCapable,
    OAuthClientCredentialsCapable,
    OAuthDeviceFlowCapable,
    OAuthMetadata,
    OAuthProviderConfig,
    OAuthProviderDeclaration,
    OAuthState,
    OAuthStatus,
)

__all__ = [
    "PythonVersion",
    "PluginInfo",
    "APIListener",
    "PluginRole",
    "PluginInterface",
    "PluginInterfaces",
    "PluginCapability",
    "API_EVENT",
    "PluginContract",
    "ImageMetadata",
    "AudioMetadata",
    "MotionDetectionPluginResponse",
    "ObjectDetectionPluginResponse",
    "AudioDetectionPluginResponse",
    "FaceDetectionPluginResponse",
    "LicensePlateDetectionPluginResponse",
    "ClassifierDetectionPluginResponse",
    "ClipDetectionInterface",
    "ClipDetectionPluginResponse",
    "ClipTextEmbeddingResult",
    "PluginAPI",
    "BasePlugin",
    "DiscoveryProvider",
    "MotionDetectionInterface",
    "ObjectDetectionInterface",
    "AudioDetectionInterface",
    "FaceDetectionInterface",
    "LicensePlateDetectionInterface",
    "ClassifierDetectionInterface",
    "get_contract_validation_errors",
    "validate_contract_consistency",
    "is_hub",
    "can_create_cameras",
    "can_provide_sensors_to_any_cameras",
    "has_interface",
    "has_capability",
    "Notification",
    "NotifierDevice",
    "NotifierInterface",
    "Severity",
    "OAuthStatus",
    "OAuthState",
    "OAuthMetadata",
    "OAuthProviderConfig",
    "OAuthProviderDeclaration",
    "OAuthCapable",
    "OAuthDeviceFlowCapable",
    "OAuthAuthCodeFlowCapable",
    "OAuthClientCredentialsCapable",
]
