from __future__ import annotations

from .config import (
    AssignedPlugin,
    BaseCamera,
    BaseCameraConfig,
    Camera,
    CameraConfig,
    CameraConfigInputSettings,
    CameraInformation,
    CameraInput,
    CameraPluginInfo,
    CameraPropertyObservableObject,
    CameraPublicProperties,
    CameraUiSettings,
    PluginAssignments,
)
from .detection import (
    AlertZone,
    AlertZoneMatch,
    AudioDetectionSettings,
    CameraDetectionSettings,
    CameraZones,
    DetectionLine,
    FaceDetectionSettings,
    LicensePlateDetectionSettings,
    MotionDetectionSettings,
    MotionZone,
    ObjectDetectionSettings,
    ObjectZone,
    PrivacyZone,
    PtzAutotrackSettings,
    SensorTriggerSettings,
    TimeWindow,
)
from .device import (
    CameraDevice,
    CameraDeviceSource,
    CameraImplementation,
    CameraSource,
    SnapshotInterface,
    StreamingInterface,
)
from .enums import (
    EVENT_TRIGGER_TYPES,
    AudioCodec,
    AudioFFmpegCodec,
    CameraActivityMode,
    CameraAspectRatio,
    CameraAspectRatioPreset,
    CameraRole,
    CameraType,
    DetectionEventState,
    DetectionEventType,
    EventTriggerType,
    LineDirection,
    MotionResolution,
    PlaybackSource,
    Point,
    ProbeAudioCodec,
    RTSPAudioCodec,
    StreamDirection,
    StreamingRole,
    VideoCodec,
    VideoFFmpegCodec,
    VideoStreamingMode,
    ZoneType,
)
from .events import (
    DetectionEvent,
    DetectionEventPayload,
    EventAttribute,
    EventDetection,
    EventSegment,
    EventTrigger,
)
from .frames import (
    CameraFrameWorkerSettings,
    FrameWorkerDecoderHardware,
    FrameWorkerDecoderSettings,
    SnapshotSettings,
)
from .notification import (
    CameraNotificationSettings,
    NotificationSpeed,
)
from .recording import (
    CameraRecordingSettings,
    RecordingMode,
    RecordingSource,
)
from .streaming import (
    AudioCodecProperties,
    AudioStreamInfo,
    FMTPInfo,
    Go2RtcRTSPSource,
    Go2RtcSnapshotSource,
    Go2RtcWSSource,
    ProbeConfig,
    ProbeStream,
    RTSPUrlOptions,
    SnapshotUrlOptions,
    StreamUrls,
    VideoCodecProperties,
    VideoStreamInfo,
)

__all__ = [
    # Types
    "CameraType",
    "ZoneType",
    "CameraRole",
    "CameraActivityMode",
    "PlaybackSource",
    "StreamingRole",
    "MotionResolution",
    "AudioCodec",
    "AudioFFmpegCodec",
    "VideoCodec",
    "VideoFFmpegCodec",
    "RTSPAudioCodec",
    "ProbeAudioCodec",
    "VideoStreamingMode",
    "CameraAspectRatio",
    "CameraAspectRatioPreset",
    "Point",
    "LineDirection",
    "StreamDirection",
    # Streaming URLs
    "Go2RtcWSSource",
    "Go2RtcRTSPSource",
    "Go2RtcSnapshotSource",
    "StreamUrls",
    # Probe
    "ProbeConfig",
    "FMTPInfo",
    "AudioCodecProperties",
    "VideoCodecProperties",
    "AudioStreamInfo",
    "VideoStreamInfo",
    "ProbeStream",
    "RTSPUrlOptions",
    "SnapshotUrlOptions",
    # Detection Events
    "DetectionEventState",
    "EventTriggerType",
    "EVENT_TRIGGER_TYPES",
    "DetectionEventType",
    "EventDetection",
    "EventAttribute",
    "EventTrigger",
    "EventSegment",
    "DetectionEvent",
    "DetectionEventPayload",
    # Detection
    "AlertZone",
    "AlertZoneMatch",
    "CameraZones",
    "MotionZone",
    "ObjectZone",
    "PrivacyZone",
    "DetectionLine",
    "MotionDetectionSettings",
    "ObjectDetectionSettings",
    "AudioDetectionSettings",
    "FaceDetectionSettings",
    "LicensePlateDetectionSettings",
    "SensorTriggerSettings",
    "PtzAutotrackSettings",
    "TimeWindow",
    "CameraDetectionSettings",
    "CameraNotificationSettings",
    "CameraRecordingSettings",
    "FrameWorkerDecoderHardware",
    "FrameWorkerDecoderSettings",
    "NotificationSpeed",
    "RecordingMode",
    "RecordingSource",
    "SnapshotSettings",
    # Config
    "CameraInformation",
    "CameraFrameWorkerSettings",
    "CameraInput",
    "CameraConfigInputSettings",
    "BaseCameraConfig",
    "CameraConfig",
    "CameraUiSettings",
    # Plugin assignments
    "AssignedPlugin",
    "PluginAssignments",
    "CameraPluginInfo",
    # Camera
    "BaseCamera",
    "Camera",
    "CameraPublicProperties",
    "CameraPropertyObservableObject",
    # Protocols
    "CameraSource",
    "CameraDeviceSource",
    "CameraDevice",
    # Camera Interfaces
    "StreamingInterface",
    "SnapshotInterface",
    "CameraImplementation",
]
